#include "gui.h"

void draw_bitboard () {

  initscr();
  start_color();
  init_pair(1, COLOR_BLACK, COLOR_WHITE);
  init_pair(2, COLOR_WHITE, COLOR_BLACK);

  // printw("♜♞♝♛♚♝♞♜\n♟♟♟♟♟♟♟♟");
  attron(COLOR_PAIR(1));
  printw(" ♜ ");
  attron(COLOR_PAIR(2));
  printw(" ♘ ");
  attron(COLOR_PAIR(1));
  printw(" ♝ ");
  attron(COLOR_PAIR(2));
  printw(" ♕ ");
  attron(COLOR_PAIR(1));
  printw(" ♚ ");
  attron(COLOR_PAIR(2));
  printw(" ♗ ");
  attron(COLOR_PAIR(1));
  printw(" ♞ ");
  attron(COLOR_PAIR(2));
  printw(" ♖ \n");

  attron(COLOR_PAIR(2));
  printw(" ♙ ");
  attron(COLOR_PAIR(1));
  printw(" ♟ ");
  attron(COLOR_PAIR(2));
  printw(" ♙ ");
  attron(COLOR_PAIR(1));
  printw(" ♟ ");
  attron(COLOR_PAIR(2));
  printw(" ♙ ");
  attron(COLOR_PAIR(1));
  printw(" ♟ ");
  attron(COLOR_PAIR(2));
  printw(" ♙ ");
  attron(COLOR_PAIR(1));
  printw(" ♟ \n");

  attron(COLOR_PAIR(1));
  printw("   ");
  attron(COLOR_PAIR(2));
  printw("   ");
  attron(COLOR_PAIR(1));
  printw("   ");
  attron(COLOR_PAIR(2));
  printw("   ");
  attron(COLOR_PAIR(1));
  printw("   ");
  attron(COLOR_PAIR(2));
  printw("   ");
  attron(COLOR_PAIR(1));
  printw("   ");
  attron(COLOR_PAIR(2));
  printw("   \n");

  attron(COLOR_PAIR(2));
  printw("   ");
  attron(COLOR_PAIR(1));
  printw("   ");
  attron(COLOR_PAIR(2));
  printw("   ");
  attron(COLOR_PAIR(1));
  printw("   ");
  attron(COLOR_PAIR(2));
  printw("   ");
  attron(COLOR_PAIR(1));
  printw("   ");
  attron(COLOR_PAIR(2));
  printw("   ");
  attron(COLOR_PAIR(1));
  printw("   \n");

  attron(COLOR_PAIR(1));
  printw("   ");
  attron(COLOR_PAIR(2));
  printw("   ");
  attron(COLOR_PAIR(1));
  printw("   ");
  attron(COLOR_PAIR(2));
  printw("   ");
  attron(COLOR_PAIR(1));
  printw("   ");
  attron(COLOR_PAIR(2));
  printw("   ");
  attron(COLOR_PAIR(1));
  printw("   ");
  attron(COLOR_PAIR(2));
  printw("   \n");

  attron(COLOR_PAIR(2));
  printw("   ");
  attron(COLOR_PAIR(1));
  printw("   ");
  attron(COLOR_PAIR(2));
  printw("   ");
  attron(COLOR_PAIR(1));
  printw("   ");
  attron(COLOR_PAIR(2));
  printw("   ");
  attron(COLOR_PAIR(1));
  printw("   ");
  attron(COLOR_PAIR(2));
  printw("   ");
  attron(COLOR_PAIR(1));
  printw("   \n");

  attron(COLOR_PAIR(1));
  printw(" ♙ ");
  attron(COLOR_PAIR(2));
  printw(" ♟ ");
  attron(COLOR_PAIR(1));
  printw(" ♙ ");
  attron(COLOR_PAIR(2));
  printw(" ♟ ");
  attron(COLOR_PAIR(1));
  printw(" ♙ ");
  attron(COLOR_PAIR(2));
  printw(" ♟ ");
  attron(COLOR_PAIR(1));
  printw(" ♙ ");
  attron(COLOR_PAIR(2));
  printw(" ♟ \n");

  attron(COLOR_PAIR(2));
  printw(" ♜ ");
  attron(COLOR_PAIR(1));
  printw(" ♘ ");
  attron(COLOR_PAIR(2));
  printw(" ♝ ");
  attron(COLOR_PAIR(1));
  printw(" ♕ ");
  attron(COLOR_PAIR(2));
  printw(" ♚ ");
  attron(COLOR_PAIR(1));
  printw(" ♗ ");
  attron(COLOR_PAIR(2));
  printw(" ♞ ");
  attron(COLOR_PAIR(1));
  printw(" ♖ \n");

  refresh();
  getch();
  endwin();
}
